zero: meta-csp: Add glibc-utils for install getent
When executing `mcumgr` using shell commands, the following error
occurs.

  Error: exec: "getent": executable file not found in $PATH

However, this error does not appear when logging directly into Zero
via SSH. The reason for this behavior is not yet understood, but to
expedite testing, we will add the `glibc-utils` package to install
`getent`.

Signed-off-by: Takuya Sasaki <takuya.sasaki@spacecubics.com>